// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKlXwAdylu9vm__bNLB8_nFa7mJIGdkwU',
    appId: '1:354306992395:web:ad919b114c9a16051c5a0e',
    messagingSenderId: '354306992395',
    projectId: 'flutter-ui-firebase-b8cf4',
    authDomain: 'flutter-ui-firebase-b8cf4.firebaseapp.com',
    storageBucket: 'flutter-ui-firebase-b8cf4.appspot.com',
    measurementId: 'G-M3L54GVT7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6GYSABHkzyrfwvw9jyBCnG-dGo9SHnA4',
    appId: '1:354306992395:android:4f4e2af564c169931c5a0e',
    messagingSenderId: '354306992395',
    projectId: 'flutter-ui-firebase-b8cf4',
    storageBucket: 'flutter-ui-firebase-b8cf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgt03OYo_5vKixDNgMH_Q9qwDOAWOQHeM',
    appId: '1:354306992395:ios:0cc351180d5b1de01c5a0e',
    messagingSenderId: '354306992395',
    projectId: 'flutter-ui-firebase-b8cf4',
    storageBucket: 'flutter-ui-firebase-b8cf4.appspot.com',
    iosClientId: '354306992395-ocptsrjr47e0u4epjc2fk4sd4en08j9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgt03OYo_5vKixDNgMH_Q9qwDOAWOQHeM',
    appId: '1:354306992395:ios:0cc351180d5b1de01c5a0e',
    messagingSenderId: '354306992395',
    projectId: 'flutter-ui-firebase-b8cf4',
    storageBucket: 'flutter-ui-firebase-b8cf4.appspot.com',
    iosClientId: '354306992395-ocptsrjr47e0u4epjc2fk4sd4en08j9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
